import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Libre_Caslon_Display, Libre_Caslon_Text } from "next/font/google";

const libreDisplay = Libre_Caslon_Display({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libreDisplay.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
